download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip", "housing.zip")
unzip("housing.zip")
housing =  read.table("household_power_consumption.txt", sep = ';', header = TRUE)
subSetData <- housing[housing$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(subSetData$Date, subSetData$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(datetime, as.numeric(subSetData$Global_active_power), type="l", xlab="", ylab="Global Active Power")
plot(datetime, as.numeric(subSetData$Voltage), type="l", xlab="datetime", ylab="Voltage")
plot(datetime, as.numeric(subSetData$Sub_metering_1), type = "c", xlab="", ylab="Energy sub metering")
lines(datetime,as.numeric(subSetData$Sub_metering_2),col="red")
lines(datetime,as.numeric(subSetData$Sub_metering_3),col="blue")
plot(datetime, as.numeric(subSetData$Global_reactive_power), type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()