download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip", "housing.zip")
unzip("housing.zip")
housing =  read.table("household_power_consumption.txt", sep = ';', header = TRUE)
subSetData <- housing[housing$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(subSetData$Date, subSetData$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("plot3.png", width=480, height=480)
plot(datetime, as.numeric(subSetData$Sub_metering_1), type = "c", xlab="", ylab="Energy sub metering")
lines(datetime,as.numeric(subSetData$Sub_metering_2),col="red")
lines(datetime,as.numeric(subSetData$Sub_metering_3),col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()